# .golangci.yml
linters:
  enable:
    - gofmt
    - goimports
    - revive
    - govet

issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: 'SA1019: package github.com/golang/protobuf/jsonpb is deprecated' # dependency of github.com/jhump/protoreflect, see https://github.com/jhump/protoreflect/issues/463
