before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/deviceinsight/kafkactl/cmd.version={{.Version}} -X github.com/deviceinsight/kafkactl/cmd.gitCommit={{.ShortCommit}} -X github.com/deviceinsight/kafkactl/cmd.buildTime={{.Date}}
    goos:
      - darwin
      - linux
      - windows

archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  files:
    - LICENSE.md
    - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'
nfpm:
  vendor: Device Insight GmbH
  homepage: https://www.device-insight.com/
  maintainer: Dirk Wilden <[dirk.wilden@device-insight.com]>
  description: A command-line interface for interaction with Apache Kafka
  license: Apache 2.0

#   formats:
#     - deb
#     - rpm

release:
  disable: true

snapcraft:
  publish: false
  summary: A command-line interface for interaction with Apache Kafka
  description: |
    A Commandline interface for Apache Kafka which provides useful features adapted from kubectl for Kubernetes.
    Multiple kafka brokers can be configured in a config file and the active broker is also persisted within the config.
    In addition kafkactl supports auto-completion for its commands as well as topic names.
  apps:
    kafkactl:
      plugs: ["home", "network"]

brews:
  - name: kafkactl
    goarm: 6

    # NOTE: make sure the url_template, the token and given repo (github or gitlab) owner and name are from the
    # same kind. We will probably unify this in the next major version like it is done with scoop.

    # Github repository to push the tap to.
    github:
      owner: deviceinsight
      name: homebrew-tap

    commit_author:
      name: goreleaserbot
      email: goreleaser@device-insight.com

    # Folder inside the repository to put the formula.
    # Default is the root folder.
    folder: Formula

    homepage: "https://github.com/deviceinsight/kafkactl"
    description: "A command-line interface for interaction with Apache Kafka"

    # Setting this will prevent goreleaser to actually try to commit the updated
    # formula - instead, the formula file will be stored on the dist folder only,
    # leaving the responsibility of publishing it to the user.
    # If set to auto, the release will not be uploaded to the homebrew tap
    # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
    # Default is false.
    skip_upload: true

