language: go
go:
- 1.11.x
addons:
  apt:
    packages:
    - rpm
    - snapd
env:
  global:
  - PATH=/snap/bin:$PATH
  - GO111MODULE=on
  - secure: L1ou057uY1CPmN3MNxMK9fCWbNfU4hDK9R2NzDVfUo2ZztNDK5/NjnySrc2jKb1UbhPJddEJSFQKbVENF8R+a1HAJI6xEieYLDbltoMSY9+iEQwOsj8nUQolaVEwvKn/MPbL3seBEoOiuwfltVeJAVZBLRkcfTXbyjRG2GGrY9fJ7h1A2EO0SKmpYmHWyvn6/NVTn5k3Gimu5k83tSKGMpCRoEEZTfhQoDTxMgOrI1S6wiHqgzLqS/sJmVhbORm115UVIGHGCssJ4NOWCI6neAfQc3V/9N3Lz8MTA3eey1d9v108/49+r72spNlyHoIjSRjLvwSksPKc0jMCDNtJyCBsmdbXz7YKt7owUXB1YFfRbRENTuyIeq2NNfGTka9JaJp86nrWc3uRC1EkGwCbOZOOMyv7ta7M+mKUGN5uqMyXA4q/75OzKl3oRmOKCs+YEGaCekfBliE5Cf+EmEmz81y2mzwKAOM4g1VrMc4ZzGoehV6v9ReMuILJ+PtqdZql6Rxmx3ZnmvvauoQJwS9ZySrLgjtysdBP8mCpWFCCrVYcCvQhrhz8XzkafywqhLJ+aBe/Wue32nv93316wk4Y17IydypzVIXD3gO8imCPXF1OD48leAa7XBWDv4g80L0Sff5aj4LFZ5eFOAVOTkamawXt5WSFEqtZ69XthZ6OxBo=
install:
- sudo snap install snapcraft --classic
after_success:
- test -n "$TRAVIS_TAG" && snapcraft login --with snap.login
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    condition: "$TRAVIS_OS_NAME = linux"
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_10ec70445363_key -iv $encrypted_10ec70445363_iv
  -in snap.login.enc -out snap.login -d
