language: go
go:
- 1.11.x
addons:
  apt:
    packages:
    - rpm
    - snapd
env:
  global:
  - PATH=/snap/bin:$PATH
  - GO111MODULE=on
  - secure: IJqWihG1mBLWyhvJJq4GKFOnsHi9uyLTImYXsE35TrJSLEXriuPuHvr5lXFG83VFFoYlXqrCHTfdW+L4zxDuVF5Y+nn57ZBdU4zidUW9Wr7dswKed0oC14T7bEBe5Ys29VECTh5+LuSbxIk7o9taPBT3wJTDUSmrJGwJRViZQI1dIXNde0o6A9PUF3cVZG13Y5rV5oDuJvpMOyCx5ESyd0d8ILnUGjKToC8udjt9Kb6DtVTT7h/VzkKE0pA99aYhRdQf0jpE/dmQcJSc5tfmnZJzLUriLlcUhYcRsAG/qsqn4RR9RgfTHl6y2gHSyK4KMggUcNPK2Dwtd1nxehrGZ2X9LUH7KNmLvEYYgqGIJm8TfsKoOHmw+N5/qVeTPj7tjiRsqZzn3L/x1IaFDnYU0Vr9bvgvlWtk09yN5OBw1RA6CKGRoE8g7UaqzDHg2cJVcoh40qUWm3TuV4UkWrnwVsClHJWt5rcw5ipCyu8E9fjjPHt/fVLk2ZI56bKL3EV75fyNOSb1FWytwPtFvH4ty9d4igDXSUxGxrW6iWiMyUeilQGQgRhRSqQbetGD17cPu75FJfukxjECN3tF5IlxAfHwPW/Gr64WrqX0PrGgTJtin2LDpSTOtENQ/c8ltDUXTe0TQ29ZPSQpBoiqkOhDqoOoVuYAQjmB7St0mv3kCYE=
install:
- sudo snap install snapcraft --classic
after_success:
- test -n "$TRAVIS_TAG" && snapcraft login --with snap.login
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    branch: "master"
    condition: "$TRAVIS_OS_NAME = linux"
    tags: true
before_deploy:
- openssl aes-256-cbc -K $encrypted_10ec70445363_key -iv $encrypted_10ec70445363_iv
  -in snap.login.enc -out snap.login -d
