language: go
go:
- 1.11.x
addons:
  apt:
    packages:
    - rpm
env:
  matrix:
  - PATH=/snap/bin:$PATH
  - GO111MODULE=on
  global:
    secure: a/cx9V/aX3iA3iW5eDZgTuNIqCnZmTSL6NbdDFugWX85SmU44maMvRc92mSiDJA7ogoIAfoXrgvAYg3qPFMbWuvAhHdB8bjCuvXIlk/nVRjNyJSBKwOxIvPcTJw0t42KuSDxx1iUUH98z9addc3dt/+bRwX5wq+ahEsmK1B/jiUuL9K/Bd/f9SHcvwVNOsk13O08nBIDBBGsw0Bobr4RGF9Hn4+WTcsH3tlbAcaPHAM+CtYOhe3N1W/v62iYzyr4jhem7z0LfGuUFsR14VcH9bA+ftYDe14BLxJQ2xaMw77Wj6YU5XbSZGAKL2YiJR2kJun8Prwr/VcPJw533i+p88x+JNvAOOWkvFBcqSYz6uGp3mmI2RIYl89E+XzFDEuXGRuhGVhfUuwsIKre4z1OjmLkK6ZM8TrVUjw9Yi2sH81GCt7pJB5dkVVmY8kx0EsNlmprjL6kYORaeP5KMrJxqjVASB8v2sCcVUNSGZ5+UEZvnpIv69p4FvfUmXkmNMunnX2vtROElB9ElbeGtlII7WlqoI5A5WOUpKmUkJveWXajKfuKPgiT1ucYAbR8QG8uibThXIRpQz0Qe3D0ggN3+x33cnaMZb3h51TYw/dHRzF/Ki9lL2a3MmAytVebBy/lupLpsFIEbUrWYEv+L2L1f96K1jFvvq1JF39oqt0L2pk=
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    condition: "$TRAVIS_OS_NAME = linux"
    tags: true
