language: go
go:
- 1.13.x
addons:
  apt:
    packages:
    - rpm
    - snapd
services:
  - docker
env:
  global:
  - PATH=/snap/bin:$PATH
  - GO111MODULE=on
  - DOCKER_USERNAME=deviceinsighttravisci
  # travis encrypt GITHUB_TOKEN=xyz --add env.global --com
  - secure: 2DkN+G+FseExExKHvvMlltvTmaVbpREBFU1T5eR6ZhOwksxtCDQrWfswh7fjzpCluwSXmf4Gm31PesPIcZdVNY03t7OxWPv8o9ol+y1DcJbw4Q5FwSxCbDVrLf6D1D2CXyqM6EXoYxU/xbgEp7M0M+l1m9dYIUXTRk++AP0oTN1psDQ4g/wb9YqhkXQhUl7GFZTv3xf8AE3L9x7Q6ezH9BFCVgYSW8XPGpGEQLBaE86x9EE4Z5pztFT1loCCOk83FCHScaCrpdhEHOtSsyhtV3RvVtiBeY0j6PkKnoWiaq8eugNABT6gPoOF1Fnw0Qfbe6SIreOlND+LKtr0K1+usTG/RWRQ/ofdqTqTo6/xMDOY6QwlM+YnPMk/wLqoR1zgLxDW8urozLWC13MtPPrFJHPlIA5WisO71Yv2HrhciFfYcFMG34JOlYvqxU4Py6qOlWIuqcFzQAFd8wI5sleC5ovsNjwa2MX9QqkLyuQaaeG8avFacN1YZtw6NBXrBUCLEkWU2sOLz7qH97WfG889XNuoB3RNe3STaL1nxnzFbNZIGXTIMIYSYlVKhrHsC6FENarpIZtwXijrRCM017EDyRbzntHd8hDvpIuyU3nLJ8CfRRiSeVKIlFlwVMA9eJ0OapHLEnxxSEnYTKU1zgt7xVUAhNqHLSzUxCZ6I7osxLI=
  # travis encrypt DOCKER_PASSWORD=xyz --add env.global --com
  - secure: 70fON+h8Vi6eau5ZJvT934TVFM7WlvEGn5tdX7IgpKqfAOvnQTzstD1oNH3s1R89SZxIrGTmvXvik0708GGAVefEQfkAuqy5RXF4phXWJU4AAt9zSTnB3tlIIr2+/y7KjKaNNKbY0xSyU1efcdoVD02LopCwfOzziWD+xthiznduP4Oz4s2WvX91K0Cy280SL6xQwcEKtz0ZGaG0QBWExnNdZgmIo+6TmybvEcUMwD5CtlZhx7KJSTCSGjJfunuaX5DHS9asdCqTMfsQPj/tcWOvLcmRbMoMhKDBH/TT9J1jPGj3wZaX3rVHQsoCV80QPlbuzFNdgYN7JdXvyhc5oM3OEupluH1d4pvhNTkObbGBaRqLJvtJHWb+fLhvH+cLDO8LFHO1Mb3Hdm9QMB4urIEAVtzj0HUAhRICyaiETmPJ93LLo/EBSVVZot/Kb/Ef0tNVshSv8Em1EBHRnOH+wSdDCf46hgiG91lQPBiYuyqrlgNJkuvN3rgltBvhndi790amA1iHSofOpGdhnaoiMAMIDVuhietCgNZff7FAUuNX4GZPmXn6EBk3Cfy2fazUj2mWhK9DJl0NOK1A84ALivaXs/mZ5SJsCNR37E+M0XK9A/7FpzNGjEpWRnoG8YvT8WJM1gkJ/5h9NGWD5BkhfV/X8kw9ewxUvvGQowziij0=
before_script:
- curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.23.6
install:
- sudo snap install snapcraft --classic
after_success:
- test -n "$TRAVIS_TAG" && openssl aes-256-cbc -K $encrypted_10ec70445363_key -iv $encrypted_10ec70445363_iv
  -in snap.login.enc -out snap.login -d
- test -n "$TRAVIS_TAG" && snapcraft login --with snap.login
- test -n "$TRAVIS_TAG" && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
- provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: gh-pages
  keep_history: true
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    branch: master
    condition: "$TRAVIS_OS_NAME = linux"
    tags: true

