language: go

go:
  - "1.11.x"

#go_import_path: github.com/deviceinsight/kafkactl

# Default for Travis and Go is to 'go get' all dependencies in 'install'. Since we use vendoring
# with checked in dependencies we skip the install step.
#install: true

#script: go test -v ./...

# calls goreleaser
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
#    tags: true
    branch: feature/go-modules 
    condition: $TRAVIS_OS_NAME = linux
- 
