contexts:
  default:
    brokers:
      - localhost:19092
      - localhost:29092
      - localhost:39092
    avro:
      schemaRegistry: localhost:18081
    kafkaversion: 2.5.0
current-context: default
