name: Lint / Test / IT

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: actions-contrib/golangci-lint@v1

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Run Unit tests
        run: make test
      - name: Upload logs
        uses: actions/upload-artifact@v2
        with:
          name: test-logs
          path: test.log

  integration_test:
    name: Integration Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # https://docs.confluent.io/platform/current/installation/versions-interoperability.html
        kafka_version: [2.6.0, 2.5.0, 2.4.0, 2.3.0]
        include:
          - kafka_version: 2.6.0
            cp_version: 6.0.1
          - kafka_version: 2.5.0
            cp_version: 5.5.2
          - kafka_version: 2.4.0
            cp_version: 5.4.3
          - kafka_version: 2.3.0
            cp_version: 5.3.4
    env:
      CP_VERSION: ${{ matrix.cp_version }}
      KAFKAVERSION: ${{ matrix.kafka_version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Run integration tests
        run: make integration_test
      - name: Upload logs
        uses: actions/upload-artifact@v2
        with:
          name: it-logs
          path: integration-test.log
