name: release

on:
  push:
    tags:
      - v*

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      -
        name: Snapcraft login
        uses: samuelmeuli/action-snapcraft@v1
        with:
          # snapcraft export-login --snaps kafkactl --channels stable -
          snapcraft_token: ${{ secrets.snapcraft_token }}
      -
        name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --debug
        env:
          # create personal access token: https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

  aur-publish:
    needs: goreleaser
    runs-on: ubuntu-latest
    steps:
      -
        name: Publish AUR package
        uses: guumaster/aur-publish-docker-action@v1
        with:
          package_name: kafkactl
          commit_username: 'github-action-bot'
          commit_email: github-action-bot@device-insight.com
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
